# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tvRemote.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_remote(object):
    def setupUi(self, remote):
        remote.setObjectName("remote")
        remote.resize(300, 350)
        remote.setMinimumSize(QtCore.QSize(300, 350))
        remote.setMaximumSize(QtCore.QSize(300, 350))
        self.centralwidget = QtWidgets.QWidget(remote)
        self.centralwidget.setObjectName("centralwidget")
        self.powerButton = QtWidgets.QPushButton(self.centralwidget)
        self.powerButton.setGeometry(QtCore.QRect(100, 20, 93, 28))
        self.powerButton.setObjectName("powerButton")
        self.muteButton = QtWidgets.QPushButton(self.centralwidget)
        self.muteButton.setGeometry(QtCore.QRect(100, 200, 93, 28))
        self.muteButton.setObjectName("muteButton")
        self.volume_label = QtWidgets.QLabel(self.centralwidget)
        self.volume_label.setGeometry(QtCore.QRect(50, 80, 81, 20))
        self.volume_label.setAlignment(QtCore.Qt.AlignCenter)
        self.volume_label.setObjectName("volume_label")
        self.channel_label = QtWidgets.QLabel(self.centralwidget)
        self.channel_label.setGeometry(QtCore.QRect(160, 80, 91, 16))
        self.channel_label.setAlignment(QtCore.Qt.AlignCenter)
        self.channel_label.setObjectName("channel_label")
        self.volumeUpButton = QtWidgets.QToolButton(self.centralwidget)
        self.volumeUpButton.setGeometry(QtCore.QRect(60, 110, 61, 31))
        self.volumeUpButton.setArrowType(QtCore.Qt.UpArrow)
        self.volumeUpButton.setObjectName("volumeUpButton")
        self.volumeDownButton = QtWidgets.QToolButton(self.centralwidget)
        self.volumeDownButton.setGeometry(QtCore.QRect(60, 150, 61, 31))
        self.volumeDownButton.setArrowType(QtCore.Qt.DownArrow)
        self.volumeDownButton.setObjectName("volumeDownButton")
        self.channelUpButton = QtWidgets.QToolButton(self.centralwidget)
        self.channelUpButton.setGeometry(QtCore.QRect(170, 110, 61, 31))
        self.channelUpButton.setArrowType(QtCore.Qt.UpArrow)
        self.channelUpButton.setObjectName("channelUpButton")
        self.channelDownButton = QtWidgets.QToolButton(self.centralwidget)
        self.channelDownButton.setGeometry(QtCore.QRect(170, 150, 61, 31))
        self.channelDownButton.setArrowType(QtCore.Qt.DownArrow)
        self.channelDownButton.setObjectName("channelDownButton")
        self.tvStats = QtWidgets.QLabel(self.centralwidget)
        self.tvStats.setGeometry(QtCore.QRect(10, 389, 291, 51))
        self.tvStats.setText("")
        self.tvStats.setAlignment(QtCore.Qt.AlignCenter)
        self.tvStats.setObjectName("tvStats")
        self.status_label = QtWidgets.QLabel(self.centralwidget)
        self.status_label.setGeometry(QtCore.QRect(30, 230, 231, 61))
        self.status_label.setText("")
        self.status_label.setObjectName("status_label")
        remote.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(remote)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 26))
        self.menubar.setObjectName("menubar")
        remote.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(remote)
        self.statusbar.setObjectName("statusbar")
        remote.setStatusBar(self.statusbar)

        self.retranslateUi(remote)
        QtCore.QMetaObject.connectSlotsByName(remote)

    def retranslateUi(self, remote):
        _translate = QtCore.QCoreApplication.translate
        remote.setWindowTitle(_translate("remote", "TV Remote"))
        self.powerButton.setText(_translate("remote", "POWER"))
        self.muteButton.setText(_translate("remote", "MUTE"))
        self.volume_label.setText(_translate("remote", "Volume"))
        self.channel_label.setText(_translate("remote", "Channel"))
        self.volumeUpButton.setText(_translate("remote", "..."))
        self.volumeDownButton.setText(_translate("remote", "..."))
        self.channelUpButton.setText(_translate("remote", "..."))
        self.channelDownButton.setText(_translate("remote", "..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    remote = QtWidgets.QMainWindow()
    ui = Ui_remote()
    ui.setupUi(remote)
    remote.show()
    sys.exit(app.exec_())
